### ISSUE TITLE
Error with USB Headset

### ISSUE THREAD

**Issue by brandylynn8403** [adammhaile/Elpis#120]
BassPlayer.BassException: Cannot find an output device matching description [Speakers / Headphones (IDT High Definition Audio CODEC)]
   at BassPlayer.BassAudioEngine.ChangeOutputDevice(String newOutputDevice)
   at Elpis.MainWindow.FinalLoad()

I get a error with my usb headset. I've tried to update drivers, Then Uninstalled and reinstalled driver. Tried uninstalling and reinstalling Elpis. No go. Nothing is working and that error above keeps appearing.

**Comment by seliver** [comment]
Can you describe when this error occurs? Like, Elpis doesn't start at all, start but then crashes, etc. Thanks

**Comment by brandylynn8403** [comment]
Yep let me grab some screenshots or a gyazo of it.

**Comment by brandylynn8403** [comment]
https://gyazo.com/3993d5af9468dc14b58354dd904e15f5 footage of it opening 

https://gyazo.com/761aa8291d6ed2397d7cc3b3c608fd22 picture of the error

**Comment by Blinkdawg15** [comment]
I'm having the exact issue, but with a slightly different error message since we don't have the same headphones.

I get: BassPlayer.BassException: Cannot find an output device matching description [Headphones (Razer Kraken USB)]
   at BassPlayer.BassAudioEngine.ChangeOutputDevice(String newOutputDevice)
   at Elpis.MainWindow.FinalLoad()

But I think I know why it's happening. I had my Krakens in one of my front USB ports and Elpis was set to use the Krakens specifically instead of the default device. I moved them to the USB port on the back of my PC and that's when issues started happening.

I did manage to fix it, though. If you go to C:>Users>(username)>appdata>roaming>elpis you should see a file titled elpis.config. Delete that and your issue should be solved. That'll make you log back in, though.

I'm sure you could edit that .config instead to use the default 'whatever Windows says', but I didn't feel like fooling with it so I just deleted it. When Elpis launches it'll create it again.

**Comment by brandylynn8403** [comment]
Omg that worked!!! <333 I was hoping one day i would be able to use it again! thanks Blink!

**Comment by Blinkdawg15** [comment]
No problem.

If anyone has this issue in the future and doesn't want to outright delete the file-

Change the last line of that elpis.config to "System_OutputDevice|Default" without the quotations.

Then you probably won't even have to log back in.

**Comment by Wires77** [comment]
Hoping to fix issues like this with the referenced enhancement.  Closing this issue in favor of that one.
