### ISSUE TITLE
Windows XP doesn't support newer versions.

### ISSUE THREAD

**Issue by a-raccoon** [adammhaile/Elpis#211]
The most recent version of Elpis I am able to run on a Windows XP machine is Elpis Portable v1.5.2.  The installers will not execute on XP, warning that the executable is invalid.  I did not go back in time to see which was the last installer to work in XP.  Fortunately the portable .zip releases works fine.  More .zip releases may be necessary going forward.

I discovered and downloaded Elpis specifically because Firefox and Chrome and Microsoft have permanently ended support for browser updates.  Pandora will no longer play in XP supported browsers.  I want to continue using Pandora on XP embedded devices where OS upgrade is impossible.

**Comment by Wires77** [comment]
Hey, I just uploaded a portable version of 1.6.  Can you check if that works for you?  Installers have been upgraded as Windows version improve, and Elpis has stopped supporting Windows XP as well due to it being officially unsupported by Microsoft.

I would encourage you to upgrade if you're able, because I won't be doing anything specific to support older versions of Windows unless pull requests are made to do so.

**Comment by a-raccoon** [comment]
Thanks.  I don't have immediate access to an XP machine right now.  It was a client's business computers and embedded devices running XP that we wanted to get Pandora working on again.  Elipis is the currently the only means for a person to utilize the Pandora radio service on XP today.
