### ISSUE TITLE
Is there any way to use from UK?

### ISSUE THREAD

**Issue by redj101** [adammhaile/Elpis#33]
I've tried using an American proxy address (no user/pass) but now it crashes before startup.

**Comment by seliver** [comment]
Hello redj. You probably are facing the issue #23, which happens when the proxy IP has got white spaces before or after it. This bug is already fixed, but it will only aired in 1.4.7 update.

In the meanwhile try going to C:\Users\<USERNAME>\AppData\Roaming\Elpis (change <USERNAME> by your username) , open the elpis.config file with the notepad and make sure that Proxy_Address field hasn't got any white spaces before or after the IP address.
Say something if the fix worked ;)

**Comment by redj101** [comment]
Wow fast reply, thanks!

Hmm, there's definitely no spaces.
I'm happy to wait for the update though, I'm only using the proxy because I get the 'Error communicating with server message' and thought it might be because I'm in the UK (Pandora not available here) so tried using an american proxy adress.

What dp ypu think of this?

**Comment by seliver** [comment]
Yes, i tried here and it does show that error when you try accessing 
with a non-US IP (i do aswell access pandora outside US).

Are you using Windows 7? Please check if you haven't got any other 
instance of Elpis running, otherwise it will not start a new one until 
you kill the old one (system tray or CTRL-ALT-DEL and look for Elpis 
there). There's an issue going on that the restart function does not 
work on windows 7 for some reason (it works on windows 8 though).

If it's not that, I would definatelly bet on the white spaces. Try 
deleting the proxy ip address and the port, and see if Elpis does starts 
now. If it does, try writing the ip and port manually in the settings 
and see if it works.

**Comment by redj101** [comment]
So how do you access it outside the US?

**Comment by seliver** [comment]
Proxy as well.

**Comment by redj101** [comment]
I tried removing the proxy and using another, it loads now but I still get the connection error.

I think I'm setting up the proxy wrong, could you instruct me?

**Comment by seliver** [comment]
Before that, what Windows version are you using?

**Comment by redj101** [comment]
Windows 7

**Comment by seliver** [comment]
To set the proxy it's pretty straight, you write the ip and the port on 
it's own field and then click Save Settings and then Restart. Now, the 
restart function on Windows 7 does not work, it's a detected but not 
solved bug yet. What you have to do is to kill Elpis manually through 
CTRL-ALT-DEL and then start Elpis and it should work by now.
And btw the proxy needs to be a working one, otherwise you will get the 
same error as without the proxy :)
Will wait for your feedback on if it worked or not ;)

**Comment by redj101** [comment]
Alright I'll try it.
Just to make sure, where do you get your proxy from?

**Comment by seliver** [comment]
xroxy

**Comment by redj101** [comment]
Alright thanks, what do you put in for username and password?

**Comment by seliver** [comment]
Nothing, as these proxies are free :)

**Comment by redj101** [comment]
I'm still getting the communication error. :(

Does it have to be a specific type of proxy?

**Comment by redj101** [comment]
I entered the ip, port and ended the program.

**Comment by seliver** [comment]
Well, we have an advancement at least, the program starts and stuff :D

**Comment by redj101** [comment]
:dancer:

**Comment by seliver** [comment]
Well, as the proxies are free, not all of them work. You have to try one 
by one until some work. I wouldn't advise you to even try the ones with 
30 ms delay as they do not work most of the times. For a faster testing 
use foxyproxy on firefox.

**Comment by redj101** [comment]
I tried another one and it worked! :dancer:

Thank you!

What's foxyproxy though?

**Comment by redj101** [comment]
Ahh VPN service.

**Comment by seliver** [comment]
Glad to hear it finally worked!
Foxyproxy is a firefox addon to use proxies more easily, not a vpn 
service :)

http://getfoxyproxy.org/
