### ISSUE TITLE
Error initializing the player engine, Elpis must close

### ISSUE THREAD

**Issue by jevdemon** [adammhaile/Elpis#60]
This happened after installing the latest beta.  The exception occurred when I first opened Elpis:
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

I'm running Windows 10, Build 10130.

**Comment by seliver** [comment]
Is this happening every time you start Elpis?
What OS are you using?

Alexey

**Comment by jevdemon** [comment]
Windows 10 Build 10130. I updated the exception to reflect this.  The 
exception went away after I rebooted (no more problems).  I will update 
the post to include this info.

**Comment by seliver** [comment]
Great! Is the issue #49 still occuring?

**Comment by jevdemon** [comment]
This issue is resolved.  Notifications are appearing as expected.

**Comment by seliver** [comment]
great, will close this and that issue then.

**Comment by seliver** [comment]
Just installed Windows 10, Elpis Works out of the box!

**Comment by zD12** [comment]
As above, other kinda useless because this was already clarified, Windows 10 does work with Elpis.

However...  I came to Github Issues for a reason, originally when I ran the installer I never got the request for administrator privileges so it couldn't actually write any files (install itself).  I waited ten or so minutes, then I ended the process in Task Manager because I never got the request.  Then when running the installer again (Windows was being stupid, and I didn't run with Admin Privileges) it requested Admin Privileges without me having to manually do anything.  Regardless, it worked the second time.   I feel silly hijacking this issue, but, I feel even more silly posting a new issue for something that's already solved.   So, that's just a heads up.
